.TH CUTTER "1" "Sep 2017" "misc" "User Commands"
.SH NAME
cutter \- remove sections from each line of a file
.SH SYNOPSIS
.B cutter
\fIOPTION\fR... [\fIFILE\fR]...
.SH DESCRIPTION
.\" Add any additional description here
.PP
Print selected parts of lines from each FILE to standard output.
.PP
.TP
\fB\-d\fR\fIDELIM\fR
.nf
use the characters specified in DELIM instead of TAB
for field delimiters
.TP
\fB\-f\fR\fILIST\fR
select only these fields;  also print any line that contains
no delimiter character, unless the \fB\-s\fR option is specified
.TP
\fB\-O\fR\fODELIM\fR
use ODELIM as the output delimiter the default is to use the
(first) input delimiter
.PP
Each LIST is made up of one or more ranges separated by commas.
Each field is written in the specified order and is written as many
times it appears implicitly or explicitly in the LIST.

Each range is one of:
.TP
\fBn\fR
n'th field, counted from 1
.TP
\fBn\fR\-
from n'th field to end of line
.TP
\fBn\fR\-\fBm\fR
from n'th to m'th field
.TP
\fB\-m\fR
from the last field to the m'th field (reversed)
.PP
If m > n then the fields are output in reverse order.
.PP
When no FILE is specified, read standard input.
.PP
.SH EXAMPLES
cutter -d: -f1,3,1 /etc/passwd # output logname:uid:logname
.SH AUTHOR
James Sainsbury <toves@sdf.lonestar.org>
.SH LICENSE
Creative Commons CC0
.br
http://creativecommons.org/publicdomain/zero/1.0/legalcode
.SH "SEE ALSO"
GNU Coreutils (cut)
.br
www.gnu.org/software/coreutils
.br
www.gnu.org/software/coreutils/manual/coreutils.html#cut-invocation
